### ISSUE TITLE
Extract widget help. 

### ISSUE THREAD

**Issue by zontarr** [tr3vorm/cmv-extract-widget#4]
Newbie here, I want to eventually do some advanced things with extract widget, but I can't even do basic things yet. I'm unable to get the format and layer list drop down menus's to populate. extract: { include: true, id: 'export', type: 'titlePane', canFloat: true, path: 'gis/dijit/Extract', title: 'Export', open: false, position: 10, options: { map: true, extractTaskURL: 'http://encdirect.noaa.gov/arcgis/rest/services/encdirect/enc_gp_approach/GPServer', defaultFormat: 'Shapefile - SHP - .shp', defaultLayer: ' enc_gp_approach' } },

**Comment by tr3vorm** [comment]
I am away until next week so not able to help out until then sorry. This widget has not been tested against the latest CMV version which may be the source of your problems.
The best place to ask is on gitter in the CMV channel

On Mon, Aug 17, 2015 at 10:34 AM -0700, "zontarr" notifications@github.com wrote:
Newbie here, I want to eventually do some advanced things with extract widget, but I can't even do basic things yet. I'm unable to get the format and layer list drop down menus's to populate. extract: { include: true, id: 'export', type: 'titlePane', canFloat: true, path: 'gis/dijit/Extract', title: 'Export', open: false, position: 10, options: { map: true, extractTaskURL: 'http://encdirect.noaa.gov/arcgis/rest/services/encdirect/enc_gp_approach/GPServer', defaultFormat: 'Shapefile - SHP - .shp', defaultLayer: ' enc_gp_approach' } },

---

Reply to this email directly or view it on GitHub:
https://github.com/tr3vorm/cmv-extract-widget/issues/4

**Comment by zontarr** [comment]
Got it! I just didn't have my GP url constructed properly. This widget does work with the latest CMV version! Next up I'm hoping to do check boxes to do multiple layer extract instead of the drop down list. Have you considered doing this? I'll report in if I get anywhere.
